name: artic-rampart-ebov
dependencies:
  - python=3.6.6
  - pip=19.3.1
  - jameshadfield::rampart
  - bioconda::snakemake=5.7.1
  - bioconda::minimap2=2.17
  - pip:
    - git+https://github.com/artic-network/Porechop.git@v0.3.1pre
  